import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    { path: '/', redirect: '/user/login' },
    { path: '/dashboard', redirect: '/dashboard/v2' },
    { path: '/user/login', component: () => import('@/views/User-login.vue') },
    { path: '/member/memberMng', component: () => import('@/views/member/memberMng.vue') },
    { path: '/member/memberMngSungChang', component: () => import('@/views/member/memberMngSungChang.vue') },
    { path: '/member/memberMngNew', component: () => import('@/views/member/memberMngNew.vue') },
    { path: '/member/account', component: () => import('@/views/member/account.vue') },
    { path: '/member/accountV2', component: () => import('@/views/member/accountV2.vue') },
    { path: '/user/userPayment', component: () => import('@/views/user/userPayment.vue') },
    { path: '/user/managerPayment', component: () => import('../views/user/managerPayment.vue') },
    { path: '/product/eventProductList', component: () => import('../views/product/eventProductList.vue') },
    { path: '/product/eventProductItem', component: () => import('../views/product/eventProductItem.vue') },
    { path: '/product/imageView', component: () => import('../views/product/imageView.vue') },
    { path: '/product/TImageEditor', component: () => import('../views/product/TImageEditor.vue') },
    { path: '/map/findCarMan', component: () => import('../views/map/findCarMan.vue') },
    { path: '/map/useGeoLocation', component: () => import('../views/map/useGeoLocation.vue') },
    // { path: '/product/eventProductManagement', component: () => import('../views/product/eventProductManagement.vue') },
    { path: '/product/productManagement', component: () => import('../views/product/productManagement.vue') },
    { path: '/product/productManagementSungChang', component: () => import('../views/product/productManagementSungChang.vue') },
    // { path: '/product/planProductManagement', component: () => import('../views/product/planProductManagement.vue') },
    // { path: '/product/planManagement', component: () => import('../views/product/planManagement.vue') },
    { path: '/order/orderManagement', component: () => import('../views/order/orderManagement.vue') },
    { path: '/order/samplePage', component: () => import('../views/order/samplePage.vue') },
    { path: '/operate/operateManagement', component: () => import('../views/operate/operateManagement.vue') },
    { path: '/operate/eventManagement', component: () => import('../views/operate/eventManagement.vue') },
    { path: '/operate/operateManagement', component: () => import('../views/operate/operateManagement.vue') },
    { path: '/operate/commonCodeManagement', component: () => import('../views/operate/commonCodeManagement.vue') },
    { path: '/client/centerAlarmAny', component: () => import('../views/client/centerAlarmAny.vue') },
    { path: '/client/clientMng', component: () => import('../views/client/clientMng.vue') },
    { path: '/client/centerMng', component: () => import('../views/client/centerMng.vue') },
    { path: '/client/centerRouteMng', component: () => import('../views/client/centerRouteMng.vue') },
    { path: '/map/maplist', component: () => import('../views/map/maplist.vue') },
    { path: '/map/nowposition', component: () => import('../views/map/nowposition.vue') },
    { path: '/map/deliveryHistory', component: () => import('../views/map/deliveryHistory.vue') },
    { path: '/map/deliveryImage', component: () => import('../views/map/deliveryImage.vue') },
    { path: '/map/deliveryImageAny', component: () => import('../views/map/deliveryImageAny.vue') },
    { path: '/aosTest', component: () => import('../views/map/aosTest.vue') },

    { path: '/dashboard/v1', component: () => import('@/views/Dashboard-v1.vue') },
    { path: '/dashboard/v2', component: () => import('@/views/Dashboard-v2.vue') },
    { path: '/dashboard/v3', component: () => import('@/views/Dashboard-v3.vue') },
    { path: '/email/inbox', component: () => import('@/views/Email-inbox.vue') },
    { path: '/email/compose', component: () => import('@/views/Email-compose.vue') },
    { path: '/email/detail', component: () => import('@/views/Email-detail.vue') },
    { path: '/widgets', component: () => import('@/views/Widgets.vue') },
    { path: '/ui/general', component: () => import('@/views/Ui-general.vue') },
    { path: '/ui/typography', component: () => import('@/views/Ui-typography.vue') },
    { path: '/ui/tabs-accordions', component: () => import('@/views/Ui-tabs-accordions.vue') },
    { path: '/ui/modal-notification', component: () => import('@/views/Ui-modal-notification.vue') },
    { path: '/ui/widget-boxes', component: () => import('@/views/Ui-widget-boxes.vue') },
    { path: '/ui/media-object', component: () => import('@/views/Ui-media-object.vue') },
    { path: '/ui/buttons', component: () => import('@/views/Ui-buttons.vue') },
    { path: '/ui/icon-fontawesome', component: () => import('@/views/Ui-icon-fontawesome.vue') },
    { path: '/ui/icon-bootstrap-icons', component: () => import('@/views/Ui-icon-bootstrap-icons.vue') },
    { path: '/ui/icon-simple-line-icons', component: () => import('@/views/Ui-icon-simple-line-icons.vue') },
    { path: '/ui/language-bar-icon', component: () => import('@/views/Ui-language-bar-icon.vue') },
    { path: '/ui/social-buttons', component: () => import('@/views/Ui-social-buttons.vue') },
    { path: '/bootstrap-5', component: () => import('@/views/Bootstrap-5.vue') },
    { path: '/form/elements', component: () => import('@/views/Form-elements.vue') },
    // { path: '/form/plugins', component: () => import('@/views/Form-plugins.vue') },
    { path: '/form/wizards', component: () => import('@/views/Form-wizards.vue') },
    { path: '/table/elements', component: () => import('@/views/Table-elements.vue') },
    { path: '/table/plugins', component: () => import('@/views/Table-plugins.vue') },
    { path: '/pos/counter-checkout', component: () => import('@/views/Pos-counter-checkout.vue') },
    { path: '/pos/customer-order', component: () => import('@/views/Pos-customer-order.vue') },
    { path: '/pos/counter-checkout', component: () => import('@/views/Pos-counter-checkout.vue') },
    { path: '/pos/kitchen-order', component: () => import('@/views/Pos-kitchen-order.vue') },
    { path: '/pos/table-booking', component: () => import('@/views/Pos-table-booking.vue') },
    { path: '/pos/menu-stock', component: () => import('@/views/Pos-menu-stock.vue') },
    { path: '/chart/js', component: () => import('@/views/Chart-js.vue') },
    { path: '/chart/apex', component: () => import('@/views/Chart-apex.vue') },
    { path: '/calendar', component: () => import('@/views/Calendar.vue') },
    { path: '/map', component: () => import('@/views/Map.vue') },
    { path: '/gallery', component: () => import('@/views/Gallery.vue') },
    { path: '/page-option/blank', component: () => import('@/views/Page-blank.vue') },
    { path: '/page-option/with-footer', component: () => import('@/views/Page-with-footer.vue') },
    { path: '/page-option/with-fixed-footer', component: () => import('@/views/Page-with-fixed-footer.vue') },
    { path: '/page-option/without-sidebar', component: () => import('@/views/Page-without-sidebar.vue') },
    { path: '/page-option/with-right-sidebar', component: () => import('@/views/Page-with-right-sidebar.vue') },
    { path: '/page-option/with-minified-sidebar', component: () => import('@/views/Page-with-minified-sidebar.vue') },
    { path: '/page-option/with-two-sidebar', component: () => import('@/views/Page-with-two-sidebar.vue') },
    { path: '/page-option/full-height', component: () => import('@/views/Page-full-height.vue') },
    { path: '/page-option/with-wide-sidebar', component: () => import('@/views/Page-with-wide-sidebar.vue') },
    { path: '/page-option/with-light-sidebar', component: () => import('@/views/Page-with-light-sidebar.vue') },
    { path: '/page-option/with-mega-menu', component: () => import('@/views/Page-with-mega-menu.vue') },
    { path: '/page-option/with-top-menu', component: () => import('@/views/Page-with-top-menu.vue') },
    { path: '/page-option/with-boxed-layout', component: () => import('@/views/Page-with-boxed-layout.vue') },
    { path: '/page-option/with-mixed-menu', component: () => import('@/views/Page-with-mixed-menu.vue') },
    { path: '/page-option/boxed-layout-with-mixed-menu', component: () => import('@/views/Page-boxed-layout-with-mixed-menu.vue') },
    { path: '/page-option/with-transparent-sidebar', component: () => import('@/views/Page-with-transparent-sidebar.vue') },
    { path: '/page-option/with-search-sidebar', component: () => import('@/views/Page-with-search-sidebar.vue') },
    { path: '/page-option/with-hover-sidebar', component: () => import('@/views/Page-with-hover-sidebar.vue') },
    { path: '/extra/timeline', component: () => import('@/views/Extra-timeline.vue') },
    { path: '/extra/coming-soon', component: () => import('@/views/Extra-coming-soon.vue') },
    { path: '/extra/search', component: () => import('@/views/Extra-search.vue') },
    { path: '/extra/invoice', component: () => import('@/views/Extra-invoice.vue') },
    { path: '/extra/error', component: () => import('@/views/Extra-error.vue') },
    { path: '/extra/profile', component: () => import('@/views/Extra-profile.vue') },
    { path: '/extra/scrum-board', component: () => import('@/views/Extra-scrum-board.vue') },
    { path: '/extra/cookie-acceptance-banner', component: () => import('@/views/Extra-cookie-acceptance-banner.vue') },
    { path: '/extra/orders', component: () => import('@/views/Extra-orders.vue') },
    { path: '/extra/order-details', component: () => import('@/views/Extra-order-details.vue') },
    { path: '/extra/products', component: () => import('@/views/Extra-products.vue') },
    { path: '/extra/product-details', component: () => import('@/views/Extra-product-details.vue') },
    { path: '/user/login-v3', component: () => import('@/views/User-login-v3.vue') },
    { path: '/user/register-v3', component: () => import('@/views/User-register-v3.vue') },
    { path: '/helper/css', component: () => import('@/views/Helper-css.vue') },
  ],
})

export default router
